modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Ecdcaeb/Add-Potion-into-Your-Food/issues"

[[mods]]
modId="add_potion"
version="${file.jarVersion}"
displayName="Add Potion into Your Food"
credits='''Idealland - they provided the framework at 1.12.2.
           ZFP - very very cute.~
           Liu Dongyu - sponsor for 1.18.2+.
'''
authors=" Liu Dongyu , Hileb"
description='''
A mod for ZFP.Using the Potion Table,the mod which is described by Taoism Deeplake as 'PPAP' add potion...
'''

[[dependencies.add_potion]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.add_potion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
