modLoader="javafml"
loaderVersion="[48,)"
license="MIT"
issueTrackerURL="https://github.com/Ecdcaeb/Add-Potion-into-Your-Food/issues"
[[mods]]
modId="add_potion"
version="${mod_version}"
displayName="Add-Potion-into-Your-Food"
displayURL="https://www.mcmod.cn/class/8478.html"
credits='''Idealland - they provided this framework.
           ZFP - very very cute.~
           Liu Dongyu - sponsor for 1.18.2+.
'''

authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.add_potion]]
   modId="forge"
   mandatory=true
   versionRange="[48,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.add_potion]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.2,1.21)"
   ordering="NONE"
   side="BOTH"
